# Generated by Django 4.1.4 on 2022-12-31 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_contactus_contactuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactuser',
            name='product',
        ),
    ]
