# Generated by Django 4.1.4 on 2023-01-04 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_profile_auth_token_profile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuser',
            name='query',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Laptop', 'Laptop'), ('Processor', 'Processor'), ('Others', 'Others')], default=234, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobiles'), ('L', 'Laptops'), ('PR', 'Processors')], max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.date(2023, 1, 4)),
        ),
    ]
